## ---------------------------
##
## Script name:
##
## Purpose of script:
##
## Author: Daniel Smith
##
## Date Created: 2020-10-22
##
## Email: dansmi@ceh.ac.uk
##
## ---------------------------


# OG Plots ----------------------------------------------------------------

library(Hmsc)
library(corrplot)

load("Models/PA/Model.RData")
pa <- output

load("Models/AbundancePoisson/Model.RData")
abupoi <- output

load("Models/Abundance/Model.RData")
abu <- output

# Species x Species -------------------------------------------------------

OmegaCor <- computeAssociations(pa)
supportLevel = 0.90

toplotrhyne <-
  ((OmegaCor[[1]]$support > supportLevel) + (OmegaCor[[1]]$support < (1 - supportLevel)) > 0) * OmegaCor[[1]]$mean

tiff(
  filename = "Plots/ResidualCorrelation_0.9.tiff",
  units = "in",
  width = 5,
  height = 5,
  res = 600
)
corrplot(toplotrhyne, method = "circle", tl.col = "black")
dev.off()

tiff(
  filename = "Plots/ResidualCorrelation_0.9.png",
  units = "in",
  width = 5,
  height = 5,
  res = 300
)
corrplot(toplotrhyne, method = "circle", tl.col = "black")
dev.off()

ggcorrplot::ggcorrplot(toplotrhyne)


toplotyear <-
  ((OmegaCor[[2]]$support > supportLevel) + (OmegaCor[[2]]$support < (1 - supportLevel)) > 0) * OmegaCor[[2]]$mean

corrplot(toplotyear, method = "color")

toplotseason <-
  ((OmegaCor[[3]]$support > supportLevel) + (OmegaCor[[3]]$support < (1 - supportLevel)) > 0) * OmegaCor[[3]]$mean

corrplot(toplotseason, method = "color")


# Species x Covariate -----------------------------------------------------

beta <- getPostEstimate(pa, parName = "Beta")

mar.default <- c(5, 4, 4, 2) + 0.1
par(mar = mar.default + c(0, 4, 0, 0))

plotBeta(
  pa,
  beta,
  supportLevel = 0.90,
  # Cov spp names or labels?
  covNamesNumbers = c(F, T),
  # Colouring
  colors = colorRampPalette(
    c(
      "#67001F",
      "#B2182B",
      "#D6604D",
      "#F4A582",
      "#FDDBC7",
      "#FFFFFF",
      "#D1E5F0",
      "#92C5DE",
      "#4393C3",
      "#2166AC",
      "#053061"
    )
  ),
  colorLevels = 200,
)



tiff(
  filename = "Plots/CovCorrelation_0.9.tiff",
  units = "in",
  width = 5,
  height = 7,
  res = 600
)

#Margins
mar.default <- c(5, 4, 4, 2) + 0.1
par(mar = mar.default + c(0, 4, 0, 0))
#Plot
plotBeta(
  pa,
  beta,
  supportLevel = 0.90,
  # Cov spp names or labels?
  covNamesNumbers = c(F, T),
  # Colouring
  colors = colorRampPalette(
    c(
      "#67001F",
      "#B2182B",
      "#D6604D",
      "#F4A582",
      "#FDDBC7",
      "#FFFFFF",
      "#D1E5F0",
      "#92C5DE",
      "#4393C3",
      "#2166AC",
      "#053061"
    )
  ),
  colorLevels = 200
)
dev.off()

png(
  filename = "Plots/CovCorrelation_0.9.png",
  units = "in",
  width = 5,
  height = 7,
  res = 300
)

#Margins
mar.default <- c(5, 4, 4, 2) + 0.1
par(mar = mar.default + c(0, 4, 0, 0))

#Plot
plotBeta(
  pa,
  beta,
  supportLevel = 0.90,
  # Cov spp names or labels?
  covNamesNumbers = c(F, T),
  # Colouring
  colors = colorRampPalette(
    c(
      "#67001F",
      "#B2182B",
      "#D6604D",
      "#F4A582",
      "#FDDBC7",
      "#FFFFFF",
      "#D1E5F0",
      "#92C5DE",
      "#4393C3",
      "#2166AC",
      "#053061"
    )
  ),
  colorLevels = 200
)
dev.off()


# Variance Partitioning ---------------------------------------------------

# VP 

vp2df <- function(vp) {
  # A function to take a variance partition generated by Hmsc
  # and turn it into a dataframe
  x <- as.data.frame(vp$vals)
  x <- rownames_to_column(x, "fixeff")
  return(x)
}

computeVariancePartitioning(pa, na.ignore = TRUE)











