## ---------------------------
##
## Script name: VPCorr
##
## Purpose of script:
##
## Author: Daniel Smith
##
## Date Created: 2020-07-20
##
## Email: dansmi@ceh.ac.uk
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------

## load up the packages we will need:

library(tidyverse)
library(cooccur)
library(Hmsc)

## ---------------------------

data <- read_rds("Data/hmscdata.rds")

# Corr

df <- data %>% select(an_maculipennis:gammarus) %>% as.matrix()

df %>% cor() %>% ggcorrplot::ggcorrplot()

# VP 

vp2df <- function(vp) {
  # A function to take a variance partition generated by Hmsc
  # and turn it into a dataframe
  x <- as.data.frame(vp$vals)
  x <- rownames_to_column(x, "fixeff")
  return(x)
}


assign('Spring', get(load("Models/Seasonal_Models_Ellenbergs/Spring.RData")))
assign('Summer', get(load("Models/Seasonal_Models_Ellenbergs/Summer.RData")))
assign('Autumn', get(load("Models/Seasonal_Models_Ellenbergs/Autumn.RData")))

model_list = list(Spring = Spring, Summer = Summer, Autumn = Autumn)

computeVariancePartitioning(Spring) %>% plotVariancePartitioning(hM = Spring, VP = .)

